global_frame: /map
robot_base_frame: base_footprint
publish_frequency: 1.0
obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.8
observation_sources: scan
scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true}
