DWAPlannerROS:
  max_trans_vel: 1.0
  min_trans_vel: 0.4
  max_vel_x: 1.0
  min_vel_x: -0.2
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 1.7
  min_rot_vel: 0.2

  acc_lim_theta: 10.0
  acc_limit_trans: 5.0
  acc_lim_x: 10.0
  acc_lim_y: 0.0
