global_costmap:
   robot_base_frame: base_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: false
   transform_tolerance: 0.25
   footprint_padding: 0.05
   static_layer: {map_topic: /map}
   furniture: {update_frequency: 1.0}
   furniture_local: {enabled: true}
   inflation_layer: {inflation_radius: .5}
   
   plugins:
   - {name: static_layer, type: 'costmap_2d::StaticLayer'}
   - {name: furniture, type: 'furniture_layer_namespace::FurnitureLayer'}
   - {name: inflation_layer, type: 'costmap_2d::InflationLayer'}