footprint: [[0.472, .319], [-0.235, 0.319], [-0.235, -0.319], [0.472, -0.319]]
recovery_behavior_enabled: true
clearing_rotation_allowed: true
base_global_planner: navfn/NavfnROS
base_local_planner: dwa_local_planner/DWAPlannerROS
